import type { RecipesList } from './recipes.types';

export const mockRecipes: RecipesList = [
  {
    id: 1,
    name: 'Spaghetti Carbonara',
    description: 'Classic Italian pasta dish with eggs, cheese, and pancetta',
    ingredients: [
      { id: '41', name: 'spaghetti', quantity: { amount: 400, unit: 'g' } },
      { id: '6', name: 'pancetta', quantity: { amount: 200, unit: 'g' }, notes: 'or guanciale' },
      { id: '7', name: 'eggs', quantity: { amount: 4, unit: 'large' } },
      { id: '16', name: 'Pecorino Romano cheese', quantity: { amount: 100, unit: 'g' }, notes: 'grated' },
      { id: '55', name: 'black pepper', notes: 'freshly ground' },
      { id: '56', name: 'salt', notes: 'for pasta water' },
    ],
    steps: [
      'Bring a large pot of salted water to boil and cook spaghetti according to package directions',
      'Cut pancetta into small cubes and fry in a large pan until crispy',
      'In a bowl, beat eggs with grated Pecorino Romano cheese and plenty of black pepper',
      'Drain pasta, reserving 1 cup of pasta water',
      'Remove pan from heat and add the hot pasta to the pancetta',
      'Quickly add the egg mixture while tossing constantly (the heat from pasta will cook eggs gently)',
      'Add reserved pasta water a little at a time if needed to create a creamy sauce',
      'Serve immediately with extra cheese and pepper',
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'medium',
    tags: ['Italian', 'pasta', 'classic'],
  },
  {
    id: 2,
    name: 'Chicken Stir Fry',
    description: 'Quick and healthy Asian-inspired chicken and vegetables',
    ingredients: [
      { id: '1', name: 'chicken breast', quantity: { amount: 500, unit: 'g' }, notes: 'cut into bite-sized pieces' },
      { id: '24', name: 'bell peppers', quantity: { amount: 2, unit: 'whole' }, notes: 'sliced' },
      { id: '21', name: 'onion', quantity: { amount: 1, unit: 'whole' }, notes: 'sliced' },
      { id: '23', name: 'garlic', quantity: { amount: 3, unit: 'cloves' }, notes: 'minced' },
      { id: '74', name: 'soy sauce', quantity: { amount: 3, unit: 'tbsp' } },
      { id: '70', name: 'sesame oil', quantity: { amount: 2, unit: 'tbsp' } },
      { id: '38', name: 'rice', quantity: { amount: 2, unit: 'cups' }, notes: 'for serving' },
    ],
    steps: [
      'Cook rice according to package instructions',
      'Cut chicken breast into bite-sized pieces',
      'Slice bell peppers and onion, mince garlic',
      'Heat wok or large pan over high heat with sesame oil',
      'Add chicken and cook until golden brown and cooked through, about 5-7 minutes',
      'Add vegetables and stir fry for 3-4 minutes until tender-crisp',
      'Add minced garlic and soy sauce, stir for 1 minute',
      'Serve immediately over cooked rice',
    ],
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: 'easy',
    tags: ['Asian', 'quick', 'healthy', 'chicken'],
  },
  {
    id: 3,
    name: 'Greek Salad',
    description: 'Fresh Mediterranean salad with feta cheese and olives',
    ingredients: [
      { id: '20', name: 'tomatoes', quantity: { amount: 4, unit: 'whole' }, notes: 'cut into chunks' },
      { id: '25', name: 'cucumber', quantity: { amount: 1, unit: 'whole' }, notes: 'cut into chunks' },
      { id: '22', name: 'red onion', quantity: { amount: 1, unit: 'whole' }, notes: 'thinly sliced' },
      { id: '15', name: 'feta cheese', quantity: { amount: 200, unit: 'g' }, notes: 'crumbled' },
      { id: '93', name: 'Kalamata olives', quantity: { amount: 1, unit: 'cup' } },
      { id: '69', name: 'olive oil', quantity: { amount: 4, unit: 'tbsp' } },
      { id: '57', name: 'dried oregano', quantity: { amount: 1, unit: 'tsp' } },
      { id: '55', name: 'black pepper', notes: 'to taste' },
      { id: '56', name: 'salt', notes: 'to taste' },
    ],
    steps: [
      'Chop tomatoes and cucumber into large chunks',
      'Slice red onion thinly',
      'Combine tomatoes, cucumber, and onion in a large bowl',
      'Add Kalamata olives',
      'Crumble feta cheese on top',
      'Drizzle with olive oil',
      'Sprinkle with dried oregano, salt, and pepper',
      'Toss gently to combine and serve immediately',
    ],
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: 'easy',
    tags: ['Mediterranean', 'vegetarian', 'salad', 'no-cook'],
  },
  {
    id: 4,
    name: 'Beef Tacos',
    description: 'Flavorful Mexican tacos with seasoned ground beef',
    ingredients: [
      { id: '2', name: 'ground beef', quantity: { amount: 500, unit: 'g' } },
      { id: '66', name: 'taco seasoning', quantity: { amount: 2, unit: 'tbsp' } },
      { id: '47', name: 'taco shells', quantity: { amount: 8, unit: 'pieces' } },
      { id: '26', name: 'lettuce', quantity: { amount: 2, unit: 'cups' }, notes: 'shredded' },
      { id: '20', name: 'tomatoes', quantity: { amount: 2, unit: 'whole' }, notes: 'diced' },
      { id: '14', name: 'cheddar cheese', quantity: { amount: 1, unit: 'cup' }, notes: 'shredded' },
      { id: '18', name: 'sour cream', notes: 'for serving' },
      { id: '79', name: 'salsa', notes: 'for serving' },
    ],
    steps: [
      'Heat a large skillet over medium-high heat',
      'Add ground beef and cook until browned, breaking it up with a spoon',
      'Drain excess fat',
      'Add taco seasoning and 1/4 cup water, stir well',
      'Simmer for 5 minutes until sauce thickens',
      'Warm taco shells according to package directions',
      'Fill each taco shell with seasoned beef',
      'Top with shredded lettuce, diced tomatoes, cheese, sour cream, and salsa',
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'easy',
    tags: ['Mexican', 'quick', 'beef'],
  },
  {
    id: 5,
    name: 'Mushroom Risotto',
    description: 'Creamy Italian rice dish with mushrooms and Parmesan',
    ingredients: [
      { id: '39', name: 'arborio rice', quantity: { amount: 300, unit: 'g' } },
      { id: '30', name: 'mushrooms', quantity: { amount: 400, unit: 'g' }, notes: 'sliced' },
      { id: '83', name: 'vegetable broth', quantity: { amount: 1, unit: 'L' }, notes: 'kept warm' },
      { id: '85', name: 'white wine', quantity: { amount: 150, unit: 'ml' } },
      { id: '21', name: 'onion', quantity: { amount: 1, unit: 'whole' }, notes: 'finely chopped' },
      { id: '23', name: 'garlic', quantity: { amount: 2, unit: 'cloves' }, notes: 'minced' },
      { id: '12', name: 'Parmesan cheese', quantity: { amount: 100, unit: 'g' }, notes: 'grated' },
      { id: '10', name: 'butter', quantity: { amount: 50, unit: 'g' } },
      { id: '69', name: 'olive oil', quantity: { amount: 2, unit: 'tbsp' } },
    ],
    steps: [
      'Heat vegetable broth in a separate pot and keep warm',
      'In a large pan, heat olive oil and half the butter',
      'Sauté chopped onion until translucent, about 5 minutes',
      'Add sliced mushrooms and cook until golden, about 5 minutes',
      'Add garlic and arborio rice, stir for 2 minutes until rice is lightly toasted',
      'Add white wine and stir until absorbed',
      'Add warm broth one ladle at a time, stirring constantly and waiting for liquid to absorb before adding more',
      'Continue for 18-20 minutes until rice is creamy and al dente',
      'Remove from heat, stir in remaining butter and Parmesan cheese',
      'Season with salt and pepper, serve immediately',
    ],
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: 'medium',
    tags: ['Italian', 'vegetarian', 'comfort-food'],
  },
  {
    id: 6,
    name: 'Banana Pancakes',
    description: 'Fluffy breakfast pancakes with fresh bananas',
    ingredients: [
      { id: '44', name: 'all-purpose flour', quantity: { amount: 200, unit: 'g' } },
      { id: '9', name: 'milk', quantity: { amount: 250, unit: 'ml' } },
      { id: '7', name: 'eggs', quantity: { amount: 2, unit: 'large' } },
      { id: '48', name: 'bananas', quantity: { amount: 2, unit: 'whole' }, notes: 'mashed' },
      { id: '91', name: 'baking powder', quantity: { amount: 2, unit: 'tsp' } },
      { id: '89', name: 'sugar', quantity: { amount: 2, unit: 'tbsp' } },
      { id: '68', name: 'vanilla extract', quantity: { amount: 1, unit: 'tsp' } },
      { id: '10', name: 'butter', notes: 'for cooking' },
      { id: '88', name: 'maple syrup', notes: 'for serving' },
    ],
    steps: [
      'In a large bowl, mash bananas with a fork',
      'Add eggs, milk, and vanilla extract, whisk to combine',
      'In another bowl, mix flour, baking powder, and sugar',
      'Add dry ingredients to wet ingredients and stir until just combined (don\'t overmix)',
      'Heat a non-stick pan or griddle over medium heat and add butter',
      'Pour 1/4 cup batter for each pancake',
      'Cook until bubbles form on surface, about 2-3 minutes',
      'Flip and cook until golden brown, another 2 minutes',
      'Serve warm with maple syrup and sliced bananas',
    ],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: 'easy',
    tags: ['breakfast', 'vegetarian', 'sweet'],
  },
];
